[project]
name = "Unit 2 Simulation Project"
version = "0.1"
description = "Python project for Unit 2 in STAT607 at UofM."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "statsmodels>=0.14.5",
    "xarray>=2025.10.1",
]

[project.optional-dependencies]
testing = [
    "pytest>=8.4.2",
]
