import numpy as np
import logging
from dataclasses import dataclass
import json
import pickle as pkl
from pathlib import Path
from typing import Union, Any

import jax.numpy as jnp
import jax


logger = logging.getLogger(__name__)


def sigmoid(x):
    return jnp.exp(x) / (1 + jnp.exp(x))


def create_covariance_matrix(n, rho=0.0, tol=1e-6):
    """
    Create an n x n covariance matrix with 1s on the diagonal and rho elsewhere.
    """
    C = np.ones((n, n)) * rho
    # This modifies in place for some reason
    np.fill_diagonal(C, 1)
    return C


def _generate_design_matrix(prngKey, N, true_beta, sigma2, cov_mat=None):
    """
    Generate the design matrix X and binary response vector y as outlined
    in Greenland (1993). The design matrix X is a binary matrix of u
    exposures, generated by thresholding correlated normal variables Z.
    Additional noise is added over the standard binomial variance for
    y | X. Finally, the alpha intercept is chosen to center the logits
    and ensure that roughly 50% of the responses are 1s.
    """

    k1, k2, k3, k4 = jax.random.split(prngKey, 4)
    # jax.debug.print(f"keys: {prngArray}")
    if cov_mat is None:
        cov_mat = jnp.eye(len(true_beta))

    Z = jax.random.multivariate_normal(
        k1,
        mean=jnp.zeros(cov_mat.shape[0]),
        cov=cov_mat,
        shape=(N,),
        method="cholesky",
    )
    c_j = jax.random.uniform(k2, minval=-0.25, maxval=0.25, shape=(cov_mat.shape[0],))
    # jax.debug.print(f"c_j values: {c_j}")

    eps_k = sigma2 * jax.random.normal(k3, shape=(N,))
    X = Z > c_j

    # add intercept that centers the logits
    alpha = -jnp.mean(X @ true_beta + eps_k)
    # jax.debug.print(f"Alpha (intercept) value: {alpha}")

    logits = alpha + X @ true_beta + eps_k
    p_i = sigmoid(logits)
    y = jax.random.binomial(k4, 1, p_i)
    # jax.debug.print(f"{jnp.sum(y)}/{N} positive responses {jnp.mean(y)}.")

    return X, y


def _generate_beta(prngKey, tau_0, tau_1, n):
    """
    Generate true regression coefficients for simulation. Interestingly,
    the beta draws are independent, despite us assuming correlation
    when estimated a parameter shrinkage term.
    """
    k1, k2, k3 = jax.random.split(prngKey, 3)
    z_i = jax.random.bernoulli(k1, p=0.2, shape=(n,))
    pi_i = tau_1 * jax.random.exponential(k2, shape=(n,))

    delta_i = tau_0 * jax.random.normal(k3, shape=(n,))
    beta = z_i * pi_i + delta_i
    return beta


# @jax.jit
def _subcall(
    prngKey, N=100, batches=1, sigma2=1.0, tau_0=1.0, tau_1=1.0, n=5, cov_mat=None
) -> tuple[jnp.ndarray, jnp.ndarray, jnp.ndarray, jnp.ndarray]:
    all_keys = jax.random.split(prngKey, batches + 1)
    new_key, keys = all_keys[0], all_keys[1:]
    if cov_mat is None:
        cov_mat = jnp.eye(n)
    true_beta = jax.vmap(_generate_beta, in_axes=(0, None, None, None))(
        keys, tau_0, tau_1, n
    )

    all_keys = jax.random.split(new_key, batches + 1)
    new_key, keys = all_keys[0], all_keys[1:]
    X, y = jax.vmap(_generate_design_matrix, in_axes=(0, None, 0, None, None))(
        keys,
        N,
        true_beta,
        sigma2,
        cov_mat,
    )
    if batches == 1:
        X = X[0]
        y = y[0]
        true_beta = true_beta[0]
        generator_state = prngKey

    return X, y, true_beta, generator_state


_subcall = jax.jit(_subcall, static_argnames=("batches", "n", "N"))


@dataclass
class SimulatedData(object):
    """
    Container for simulated data and parameters.
    Also includes methods for saving and loading from disk.

    Attributes
    ----------
    X : np.ndarray
        Design matrix of shape (N, n).
    y : np.ndarray
        Binary response vector of shape (N,).
    true_beta : np.ndarray
        True regression coefficients of shape (n,).
    n : int
        See DatasetGenerator.
    rho : float
        See DatasetGenerator.
    tau_0 : float
        See DatasetGenerator.
    tau_1 : float
        See DatasetGenerator.
    sigma2 : float
        See DatasetGenerator.
    rng : np.random.Generator
        Random number generator used for reproducibility.
    """

    X: jnp.ndarray
    y: jnp.ndarray
    true_beta: jnp.ndarray
    rho: float
    tau_0: float
    tau_1: float
    sigma2: float
    generator_state: Any

    def __post_init__(self):
        self.N, self.n = self.X.shape[0], self.X.shape[1]

    def __repr__(self):
        """
        More detailed representation for debugging.
        """
        return (
            f"<SimulatedData(N={self.N}, n={self.n}, rho={self.rho}, tau_0={self.tau_0}, "
            f"tau_1={self.tau_1}, sigma2={self.sigma2}, "
            f"X_shape={self.X.shape}, y_shape={self.y.shape})>"
        )

    def __iter__(self):
        """
        Allow unpacking like a tuple: X, y, true_beta = simulated_data
        """
        yield from (self.X, self.y, self.true_beta)

    def __str__(self) -> str:
        return json.dumps(self.__dict__)

    def __create_filename(self):
        return Path(
            f"simdata_N{self.N}n{self.n}_rho={self.rho}_tau0={self.tau_0}_"
            f"tau1={self.tau_1}_sigma2={self.sigma2}.pkl"
        )

    def save(self, output_dir: Union[Path, str]):
        """
        Save the simulated data for later, along with RNG state for
        reproducibility.

        Parameters
        ----------
        output_dir : Union[Path, str]
            Directory to save the data file in. Note that you provide a
            directory because the filename is decided based on the parameters
            used in the generation of the data.
        """
        output_file = Path(output_dir) / self.__create_filename()
        output_file.parent.mkdir(parents=True, exist_ok=True)
        logging.debug(f"Saving simulated data to {output_file}")
        with open(output_file, "wb") as f:
            pkl.dump(self, f)
        logging.debug(f"Simulated data saved to {output_file}")
        return output_file

    @classmethod
    def load(cls, filepath):
        """
        Load simulated data from disk. Note that this can be used to load
        any pickled object, so we check that the loaded object is of the
        correct type.

        Parameters
        ----------
        filepath : Union[Path, str]
            Path to the saved data file.

        Returns
        -------
        SimulatedData
        """
        with open(filepath, "rb") as f:
            data = pkl.load(f)
        assert isinstance(data, cls), f"Loaded data is not of type {cls.__name__}"
        return data


class DatasetGenerator(object):
    def __init__(self, n=5, rho=0.0, tau_0=1.0, tau_1=1.0, sigma2=1.0):
        """
        Constructor class for generating simulated datasets with the given
        parameters. This class utilizes a callable interface, so when generating
        from this class, you use it like a function (e.g. `generate_data(N)`),
        where N is the number of samples to generate.

        Parameters
        ----------
        n : int
            Number of predictors.
        rho : float
            Correlation parameter used in covariance matrix generation of Z
            values. Combined with draws from a uniform (-0.25, 0.25) uniform
            distribution to create correlated binary predictors in X,
            representing exposures.
        tau_0 : float
            Standard deviation for noise (δ_i) in true beta generation.
        tau_1 : float
            Scale parameter for the exponential distribution in beta generation,
            the actual beta effect. For any given beta, there is an
            80% change that this simulated value is ignored and assigned a 0.
        sigma2 : float
            Standard deviation of the noise (ϵ_k) added to the logits for
            individual rows, i.e. additional noise in the log-odds not accounted
            for by the binomial distribution assumed on Y conditional on X.
        rng : np.random.Generator
            Random number generator used for reproducibility.
        """
        self.n = n
        self.rho = rho
        self.tau_0 = tau_0
        self.tau_1 = tau_1
        self.sigma2 = sigma2
        self.cov_mat = create_covariance_matrix(n, rho)

    def __call__(self, prngKey, N=100, batches=1) -> SimulatedData:
        X, y, true_beta, generator_state = _subcall(
            prngKey=prngKey,
            N=N,
            batches=batches,
            sigma2=self.sigma2,
            tau_0=self.tau_0,
            tau_1=self.tau_1,
            n=self.n,
            cov_mat=self.cov_mat,
        )
        return SimulatedData(
            X,
            y,
            true_beta,
            self.rho,
            self.tau_0,
            self.tau_1,
            self.sigma2,
            generator_state,
        )
